### ISSUE TITLE
turns 'undefined' objects in strings

### ISSUE THREAD

**Issue by dominictarr** [BonsaiDen/Fomatto#2]
``` js
var f = new (require('fomatto').Formatter)()
f('qq_{x}_qq', {x: undefined})
```

returns `'qq_[object Object]_qq'`

which is not right, should work the same as:

``` js
var f = new (require('fomatto').Formatter)()
f('qq_{0}_qq', undefined)
```

which returns `'qq_undefined_qq'`

**Comment by BonsaiDen** [comment]
Fixed https://github.com/BonsaiDen/Fomatto/commit/a0ab78c13ce53f91410c2a5bdd20ab5fdcae819d
